# Generated by Django 5.2.7 on 2025-12-03 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('slug', models.SlugField(unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BoardComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(blank=True, default='', max_length=20)),
                ('guest_pw_hash', models.CharField(blank=True, default='', max_length=256)),
                ('body', models.TextField()),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='boardpost',
            options={'ordering': ['-pinned', '-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='boardpost',
            name='board_board_created_e9ba11_idx',
        ),
        migrations.RemoveIndex(
            model_name='boardpost',
            name='board_board_is_publ_38fd65_idx',
        ),
        migrations.AddField(
            model_name='boardpost',
            name='allow_comments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='boardpost',
            name='guest_name',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='boardpost',
            name='guest_pw_hash',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='boardpost',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boardpost',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boardpost',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='board.boardcategory'),
        ),
        migrations.AddIndex(
            model_name='boardpost',
            index=models.Index(fields=['-pinned', '-created_at'], name='board_board_pinned_1df3e2_idx'),
        ),
        migrations.AddIndex(
            model_name='boardpost',
            index=models.Index(fields=['is_published', 'is_deleted', '-created_at'], name='board_board_is_publ_d7f90b_idx'),
        ),
        migrations.AddIndex(
            model_name='boardpost',
            index=models.Index(fields=['category', '-created_at'], name='board_board_categor_b9aff3_idx'),
        ),
        migrations.AddField(
            model_name='boardcomment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boardcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='board.boardpost'),
        ),
        migrations.AddIndex(
            model_name='boardcomment',
            index=models.Index(fields=['post', 'created_at'], name='board_board_post_id_ee5980_idx'),
        ),
        migrations.AddIndex(
            model_name='boardcomment',
            index=models.Index(fields=['is_hidden', 'is_deleted', 'created_at'], name='board_board_is_hidd_f0c2d3_idx'),
        ),
    ]
