# Generated by Django 5.2.7 on 2025-12-03 13:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_boardcategory_boardcomment_alter_boardpost_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardpost',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='boardpost',
            name='board_board_pinned_1df3e2_idx',
        ),
        migrations.AddField(
            model_name='boardcategory',
            name='is_notice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boardcomment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boardcomment',
            name='hidden_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boardpost',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='board/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='boardpost',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='boardpost',
            index=models.Index(fields=['-created_at'], name='board_board_created_e9ba11_idx'),
        ),
    ]
