# Generated by Django 5.2.7 on 2025-12-03 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_boardpost_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('post', 'post'), ('comment', 'comment')], max_length=10)),
                ('reason', models.CharField(default='spam', max_length=30)),
                ('message', models.TextField(blank=True, default='')),
                ('reporter_fp', models.CharField(blank=True, default='', max_length=16)),
                ('status', models.CharField(choices=[('open', 'open'), ('resolved', 'resolved'), ('rejected', 'rejected')], default='open', max_length=12)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='board.boardcomment')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board_reports_handled', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='board.boardpost')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='board_board_status_247cff_idx'), models.Index(fields=['target_type', '-created_at'], name='board_board_target__93cd17_idx')],
            },
        ),
    ]
