# Generated by Django 5.2.7 on 2025-12-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_boardreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardAbuseKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=200)),
                ('is_regex', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['enabled', '-created_at'], name='board_board_enabled_cacf8d_idx')],
            },
        ),
    ]
