# Generated by Django 5.2.7 on 2025-12-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_boardabusekeyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardcomment',
            name='creator_fp',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
