# Generated by Django 5.2.7 on 2025-12-03 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_boardcomment_creator_fp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='boardpost',
            name='creator_fp',
            field=models.CharField(blank=True, db_index=True, default='', max_length=16),
        ),
        migrations.CreateModel(
            name='BoardAdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_name', models.CharField(blank=True, max_length=80)),
                ('action', models.CharField(choices=[('bulk_resolve', 'Bulk Resolve'), ('bulk_reject', 'Bulk Reject'), ('report_action', 'Report Action'), ('system', 'System')], db_index=True, max_length=32)),
                ('done', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(blank=True, max_length=16)),
                ('q', models.CharField(blank=True, max_length=160)),
                ('auto_only', models.BooleanField(default=False)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('report_ids', models.JSONField(blank=True, default=list)),
                ('report_ids_preview', models.CharField(blank=True, max_length=300)),
                ('report_ids_blob', models.CharField(blank=True, db_index=True, max_length=340)),
                ('note', models.TextField(blank=True)),
                ('path', models.CharField(blank=True, max_length=200)),
                ('query_string', models.TextField(blank=True)),
                ('ip', models.CharField(blank=True, max_length=64)),
                ('ua', models.CharField(blank=True, max_length=200)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board_admin_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'action'], name='board_board_created_281437_idx'), models.Index(fields=['actor_name'], name='board_board_actor_n_e9d02f_idx')],
            },
        ),
    ]
