# Generated by Django 5.2.7 on 2026-01-02 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_boardpost_creator_fp_boardadminactionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardpost',
            name='is_secret',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
