# Generated by Django 5.2.7 on 2025-10-27 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RagSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='설정 항목 이름. 예: AUTO_INGEST_AFTER_GEMINI', max_length=100, unique=True)),
                ('value', models.TextField(blank=True, help_text='설정 값 (문자열로 저장. true/false/숫자도 문자열로 저장)')),
                ('description', models.CharField(blank=True, help_text='사람이 읽는 설명', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'RAG 설정값',
                'verbose_name_plural': 'RAG 설정값들',
            },
        ),
    ]
