# Generated by Django 5.2.7 on 2025-10-27 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ragsetting',
            options={'ordering': ['-updated_at'], 'verbose_name': 'RAG 설정', 'verbose_name_plural': 'RAG 설정'},
        ),
        migrations.RemoveField(
            model_name='ragsetting',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ragsetting',
            name='key',
        ),
        migrations.RemoveField(
            model_name='ragsetting',
            name='value',
        ),
        migrations.AddField(
            model_name='ragsetting',
            name='auto_ingest_after_gemini',
            field=models.BooleanField(default=True, help_text='웹 검색(Gemini) 수행 뒤 자동으로 뉴스까지 크롤링 / 인덱싱할지 여부'),
        ),
        migrations.AddField(
            model_name='ragsetting',
            name='chroma_collection',
            field=models.CharField(blank=True, help_text='Chroma 컬렉션 이름(읽기 전용 안내용)', max_length=200),
        ),
        migrations.AddField(
            model_name='ragsetting',
            name='chroma_db_dir',
            field=models.CharField(blank=True, help_text='Chroma DB 디렉토리 경로(읽기 전용 안내용)', max_length=300),
        ),
        migrations.AddField(
            model_name='ragsetting',
            name='news_topk',
            field=models.IntegerField(default=5, help_text='구글 뉴스 RSS에서 가져올 기사 수'),
        ),
        migrations.AddField(
            model_name='ragsetting',
            name='rag_fallback_topk',
            field=models.IntegerField(default=12, help_text='RAG 확장 topk'),
        ),
        migrations.AddField(
            model_name='ragsetting',
            name='rag_force_answer',
            field=models.BooleanField(default=True, help_text='RAG가 직접 근거가 부족해도 상식으로라도 답변을 보완할지'),
        ),
        migrations.AddField(
            model_name='ragsetting',
            name='rag_max_sources',
            field=models.IntegerField(default=8, help_text='RAG 답변에 노출할 최대 소스 개수'),
        ),
        migrations.AddField(
            model_name='ragsetting',
            name='rag_query_topk',
            field=models.IntegerField(default=5, help_text='RAG 1차 topk'),
        ),
        migrations.AddField(
            model_name='ragsetting',
            name='web_ingest_to_chroma',
            field=models.BooleanField(default=True, help_text='웹 검색 결과/뉴스를 Chroma에 저장할지(0이면 아예 저장 안 함)'),
        ),
        migrations.CreateModel(
            name='MyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('web', 'Web QA'), ('rag', 'RAG QA'), ('ingest', 'News Ingest')], max_length=16)),
                ('question', models.TextField()),
                ('answer_head', models.TextField(blank=True, help_text='모델 답변(앞부분/요약)')),
                ('ok', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True)),
                ('meta', models.JSONField(blank=True, default=dict, help_text='추가 정보(청크 수, ingest 결과 등)')),
                ('remote_addr', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '질의 로그',
                'verbose_name_plural': '질의 로그',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['mode', 'created_at'], name='ragapp_mylo_mode_bd5498_idx')],
            },
        ),
    ]
