# Generated by Django 5.2.7 on 2025-10-27 04:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragapp', '0002_alter_ragsetting_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mylog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='ragsetting',
            options={'verbose_name': 'RAG 설정', 'verbose_name_plural': 'RAG 설정'},
        ),
        migrations.RemoveIndex(
            model_name='mylog',
            name='ragapp_mylo_mode_bd5498_idx',
        ),
        migrations.RenameField(
            model_name='mylog',
            old_name='question',
            new_name='query_text',
        ),
        migrations.RemoveField(
            model_name='mylog',
            name='answer_head',
        ),
        migrations.RemoveField(
            model_name='mylog',
            name='error',
        ),
        migrations.RemoveField(
            model_name='mylog',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='mylog',
            name='user_agent',
        ),
        migrations.RemoveField(
            model_name='ragsetting',
            name='chroma_collection',
        ),
        migrations.RemoveField(
            model_name='ragsetting',
            name='chroma_db_dir',
        ),
        migrations.RemoveField(
            model_name='ragsetting',
            name='rag_force_answer',
        ),
        migrations.AddField(
            model_name='mylog',
            name='answer_preview',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='mylog',
            name='extra',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ragsetting',
            name='answer_link_max',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='ragsetting',
            name='crawl_answer_links',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ragsetting',
            name='embed_chunk_overlap',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='ragsetting',
            name='embed_chunk_size',
            field=models.IntegerField(default=1600),
        ),
        migrations.AlterField(
            model_name='mylog',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mylog',
            name='mode',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='ragsetting',
            name='auto_ingest_after_gemini',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ragsetting',
            name='news_topk',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='ragsetting',
            name='rag_fallback_topk',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='ragsetting',
            name='rag_max_sources',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='ragsetting',
            name='rag_query_topk',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='ragsetting',
            name='web_ingest_to_chroma',
            field=models.BooleanField(default=True),
        ),
    ]
