# Generated by Django 5.2.7 on 2025-10-27 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragapp', '0003_alter_mylog_options_alter_ragsetting_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mylog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ragsetting',
            options={},
        ),
        migrations.RemoveField(
            model_name='mylog',
            name='answer_preview',
        ),
        migrations.RemoveField(
            model_name='mylog',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='mylog',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='mylog',
            name='ok',
        ),
        migrations.RemoveField(
            model_name='mylog',
            name='query_text',
        ),
        migrations.RemoveField(
            model_name='mylog',
            name='remote_addr',
        ),
        migrations.RemoveField(
            model_name='ragsetting',
            name='answer_link_max',
        ),
        migrations.RemoveField(
            model_name='ragsetting',
            name='embed_chunk_overlap',
        ),
        migrations.RemoveField(
            model_name='ragsetting',
            name='embed_chunk_size',
        ),
        migrations.AddField(
            model_name='mylog',
            name='extra_json',
            field=models.JSONField(blank=True, default=dict, help_text='결과 요약, 에러 메시지, 저장 chunk 수 등 자유롭게'),
        ),
        migrations.AddField(
            model_name='mylog',
            name='mode_text',
            field=models.CharField(blank=True, default='', help_text="무슨 작업인지. 예: 'admin_crawl', 'api_ingest' 등", max_length=64),
        ),
        migrations.AddField(
            model_name='mylog',
            name='ok_flag',
            field=models.BooleanField(default=True, help_text='성공 여부'),
        ),
        migrations.AddField(
            model_name='mylog',
            name='query',
            field=models.TextField(blank=True, default='', help_text='사용된 키워드/질문 등'),
        ),
        migrations.AddField(
            model_name='mylog',
            name='remote_addr_text',
            field=models.CharField(blank=True, default='', help_text='요청자 IP 등', max_length=64),
        ),
        migrations.AddField(
            model_name='ragsetting',
            name='chroma_collection',
            field=models.CharField(blank=True, default='web_rag', help_text='Chroma 컬렉션 이름 (기존 컬렉션에 계속 append)', max_length=128),
        ),
        migrations.AddField(
            model_name='ragsetting',
            name='chroma_db_dir',
            field=models.CharField(blank=True, default='', help_text='로컬 Chroma DB 폴더 경로', max_length=512),
        ),
        migrations.AlterField(
            model_name='mylog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='로그 생성 시각'),
        ),
        migrations.AlterField(
            model_name='ragsetting',
            name='auto_ingest_after_gemini',
            field=models.BooleanField(default=True, help_text='웹 검색(Gemini) 직후 자동으로 인덱싱까지 수행할지 여부'),
        ),
        migrations.AlterField(
            model_name='ragsetting',
            name='crawl_answer_links',
            field=models.BooleanField(default=True, help_text='답변 본문 속 URL까지 따라가서 본문 크롤링/인덱싱할지'),
        ),
        migrations.AlterField(
            model_name='ragsetting',
            name='news_topk',
            field=models.IntegerField(default=5, help_text='구글 뉴스 RSS에서 긁어올 기사 수'),
        ),
        migrations.AlterField(
            model_name='ragsetting',
            name='rag_fallback_topk',
            field=models.IntegerField(default=12, help_text='RAG 2차(확장) retrieval top-k'),
        ),
        migrations.AlterField(
            model_name='ragsetting',
            name='rag_max_sources',
            field=models.IntegerField(default=8, help_text='최종 답변에 노출할 근거 source 개수 상한'),
        ),
        migrations.AlterField(
            model_name='ragsetting',
            name='rag_query_topk',
            field=models.IntegerField(default=5, help_text='RAG 1차 retrieval top-k'),
        ),
        migrations.AlterField(
            model_name='ragsetting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='이 레코드를 마지막으로 저장한 시각'),
        ),
        migrations.AlterField(
            model_name='ragsetting',
            name='web_ingest_to_chroma',
            field=models.BooleanField(default=True, help_text='검색 결과를 Chroma에 저장(인덱싱)할지 여부'),
        ),
    ]
