# Generated by Django 5.2.7 on 2025-10-28 08:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragapp', '0004_alter_mylog_options_alter_ragsetting_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('mode', models.CharField(choices=[('gemini', 'Gemini/Web 검색 답변'), ('rag', 'RAG 기반 답변')], db_index=True, help_text='어떤 엔진이 답변했는지 (gemini / rag)', max_length=20)),
                ('question', models.TextField(help_text='사용자가 실제로 입력한 질문')),
                ('answer_excerpt', models.TextField(blank=True, help_text='답변 일부(요약본). 너무 길면 앞부분만 잘라서 저장')),
                ('client_ip', models.GenericIPAddressField(blank=True, help_text='요청 보낸 클라이언트 IP (없으면 비워둘 수 있음)', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
