# Generated by Django 5.2.7 on 2025-10-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragapp', '0005_chatquerylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatquerylog',
            name='error_msg',
            field=models.TextField(blank=True, help_text='에러가 났다면 스택 대신 요약 메시지'),
        ),
        migrations.AddField(
            model_name='chatquerylog',
            name='feedback',
            field=models.CharField(blank=True, help_text="사용자 피드백 (예: 'up', 'down')", max_length=10),
        ),
        migrations.AddField(
            model_name='chatquerylog',
            name='is_error',
            field=models.BooleanField(default=False, help_text='이 호출이 실패했는지 여부 (예외 등)'),
        ),
        migrations.AlterField(
            model_name='chatquerylog',
            name='answer_excerpt',
            field=models.TextField(blank=True, help_text='사용자에게 돌려준 답변의 앞부분 (요약/미리보기)'),
        ),
        migrations.AlterField(
            model_name='chatquerylog',
            name='client_ip',
            field=models.GenericIPAddressField(blank=True, help_text='요청자 IP (없으면 비워둘 수 있음)', null=True),
        ),
        migrations.AlterField(
            model_name='chatquerylog',
            name='mode',
            field=models.CharField(choices=[('faq', 'FAQ (qa_data.py)'), ('rag', 'RAG 검색'), ('gemini', 'Gemini / 웹 검색'), ('blocked', '차단/정책 위반')], db_index=True, help_text='어떤 엔진 또는 단계가 최종 응답했는지', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatquerylog',
            name='question',
            field=models.TextField(help_text='사용자가 실제로 입력한 질문 원문'),
        ),
    ]
