# Generated by Django 5.2.7 on 2025-10-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragapp', '0006_chatquerylog_error_msg_chatquerylog_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatquerylog',
            name='was_helpful',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='chatquerylog',
            name='feedback',
            field=models.TextField(blank=True, default=''),
        ),
    ]
