# Generated by Django 5.2.7 on 2025-10-28 12:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragapp', '0007_chatquerylog_was_helpful_alter_chatquerylog_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='사용자가 물어볼 수 있는 형태 그대로 적어주세요.', verbose_name='질문')),
                ('answer', models.TextField(help_text='우리가 공식적으로 안내할 답변', verbose_name='답변')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ 항목',
                'verbose_name_plural': 'FAQ 항목들',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
    ]
