# Generated by Django 5.2.7 on 2025-10-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragapp', '0008_faqentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('answer_type', models.CharField(choices=[('rag', 'RAG'), ('gemini', 'Gemini'), ('other', 'Other')], default='rag', max_length=20)),
                ('is_helpful', models.BooleanField()),
                ('sources', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('keyword', models.CharField(max_length=200)),
                ('total_candidates', models.IntegerField(default=0)),
                ('ingested_count', models.IntegerField(default=0)),
                ('skipped_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('detail', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
