# Generated by Django 5.2.7 on 2025-10-28 14:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragapp', '0009_feedback_ingesthistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='sources',
        ),
        migrations.AddField(
            model_name='feedback',
            name='sources_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='answer',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='answer_type',
            field=models.CharField(choices=[('gemini', 'Gemini / Web 요약'), ('rag', 'RAG 답변'), ('other', '기타 / QARAG 등 기타 응답')], db_index=True, default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='is_helpful',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='question',
            field=models.TextField(blank=True, default=''),
        ),
    ]
