# Generated by Django 5.2.7 on 2025-10-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragapp', '0010_remove_feedback_sources_feedback_sources_json_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='answer_type',
            field=models.CharField(choices=[('gemini', 'Gemini / Web 요약'), ('rag', 'RAG 답변'), ('other', '기타 / 기타 응답')], db_index=True, default='other', max_length=20),
        ),
    ]
