# Generated by Django 5.2.7 on 2025-10-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragapp', '0011_alter_feedback_answer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatquerylog',
            name='feedback',
            field=models.TextField(blank=True, default='', help_text='유저가 남긴 자유 코멘트 (선택)'),
        ),
        migrations.AlterField(
            model_name='chatquerylog',
            name='was_helpful',
            field=models.BooleanField(blank=True, default=None, help_text='유저가 이 답변을 도움이 됐다고 했는지 (True/False/아직없음)', null=True),
        ),
    ]
