# Generated by Django 5.2.7 on 2025-11-02 00:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragapp', '0012_alter_chatquerylog_feedback_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.CharField(db_index=True, default='system', help_text='actor: system/admin/user 등', max_length=64)),
                ('action', models.CharField(db_index=True, help_text='예: consent.recorded, dsr.processed, purge.run', max_length=64)),
                ('target_model', models.CharField(blank=True, db_index=True, default='', help_text='타깃 모델명', max_length=64)),
                ('target_pk', models.CharField(blank=True, db_index=True, default='', help_text='타깃 PK(문자열 보관)', max_length=64)),
                ('notes', models.TextField(blank=True, default='', help_text='요약/설명')),
                ('extra', models.JSONField(blank=True, help_text='부가 JSON', null=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ConsentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('session_key', models.CharField(blank=True, db_index=True, default='', help_text='Django 세션 키(증빙용)', max_length=64)),
                ('ip_hash', models.CharField(blank=True, db_index=True, default='', help_text='요청자 IP의 해시/익명화 표현(원시 IP 미저장)', max_length=64)),
                ('user_agent', models.CharField(blank=True, default='', help_text='User-Agent (최대 400자)', max_length=400)),
                ('consent_type', models.CharField(db_index=True, default='required', help_text='required / optional / marketing 등 구분', max_length=32)),
                ('version', models.CharField(db_index=True, default='v1', help_text='프런트에서 전달한 버전 문자열(문서 연결이 안 될 때 사용)', max_length=32)),
                ('scope', models.CharField(db_index=True, default='session', help_text='세션/계정/기간 등 범위 표기용', max_length=32)),
                ('artifact_hash', models.CharField(blank=True, default='', help_text='동의 스냅샷/아티팩트 해시 (선택)', max_length=128)),
                ('extra', models.JSONField(blank=True, help_text='프론트에서 전달한 부가 데이터(FormData/JSON)', null=True)),
                ('legal_hold', models.BooleanField(db_index=True, default=False, help_text='법적 보존 필요 시 True (자동 파기 제외)')),
                ('delete_at', models.DateTimeField(blank=True, db_index=True, help_text='이 시각 이후 정기 파기 대상(RETENTION_DAYS_CONSENT)', null=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DataErasureTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('channel', models.CharField(db_index=True, default='web', help_text='web/form/email 등', max_length=32)),
                ('requester_token', models.CharField(blank=True, default='', help_text='요청자 확인 토큰(해시/토큰 일부 등, 원문 미보관 권장)', max_length=128)),
                ('target_ip_hash', models.CharField(blank=True, db_index=True, default='', help_text='삭제 대상 식별 키(익명/해시 IP 표현)', max_length=64)),
                ('scope', models.CharField(default='chatlog,feedback,consent', help_text='삭제 범위 힌트(comma: chatlog,feedback,consent)', max_length=64)),
                ('reason', models.TextField(blank=True, default='', help_text='요청 사유/코멘트')),
                ('status', models.CharField(choices=[('open', '접수'), ('processing', '처리중'), ('done', '완료'), ('rejected', '거절')], db_index=True, default='open', max_length=16)),
                ('processed_by', models.CharField(blank=True, default='system', help_text='처리자(계정명/시스템)', max_length=64)),
                ('result_json', models.JSONField(blank=True, help_text='처리 결과 요약(삭제된 건수, 테이블별 상세 등)', null=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CrawlNewsProxy',
            fields=[
            ],
            options={
                'verbose_name': '뉴스 크롤 & 인덱싱',
                'verbose_name_plural': '뉴스 크롤 & 인덱싱',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ragapp.ragsetting',),
        ),
        migrations.CreateModel(
            name='FaqSuggestProxy',
            fields=[
            ],
            options={
                'verbose_name': 'FAQ 후보 추천',
                'verbose_name_plural': 'FAQ 후보 추천',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ragapp.faqentry',),
        ),
        migrations.AlterModelOptions(
            name='chatquerylog',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AddField(
            model_name='chatquerylog',
            name='consent_version',
            field=models.CharField(blank=True, default='', help_text='동의 문구/문서 버전 문자열(선택)', max_length=32),
        ),
        migrations.AddField(
            model_name='chatquerylog',
            name='delete_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='보존기간 경과 시점(RETENTION_DAYS_CHATLOG)', null=True),
        ),
        migrations.AddField(
            model_name='chatquerylog',
            name='legal_basis',
            field=models.CharField(choices=[('consent', '동의(Consent)'), ('contract', '계약 이행(Contract)'), ('legitimate_interest', '정당한 이익(Legitimate Interest)'), ('legal_obligation', '법적 의무(Legal Obligation)'), ('other', '기타')], db_index=True, default='consent', help_text='데이터 처리의 법적 근거', max_length=32),
        ),
        migrations.AddField(
            model_name='chatquerylog',
            name='legal_hold',
            field=models.BooleanField(db_index=True, default=False, help_text='법적 보존 필요 시 True (자동 파기 제외)'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='client_ip',
            field=models.CharField(blank=True, db_index=True, default='', help_text='요청자 IP의 해시/익명화 표현(원시 IP 미저장)', max_length=64),
        ),
        migrations.AddField(
            model_name='feedback',
            name='consent_version',
            field=models.CharField(blank=True, default='', help_text='동의 문구/문서 버전 문자열(선택)', max_length=32),
        ),
        migrations.AddField(
            model_name='feedback',
            name='delete_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='보존기간 경과 시점(RETENTION_DAYS_FEEDBACK)', null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='legal_basis',
            field=models.CharField(choices=[('consent', '동의(Consent)'), ('contract', '계약 이행(Contract)'), ('legitimate_interest', '정당한 이익(Legitimate Interest)'), ('legal_obligation', '법적 의무(Legal Obligation)'), ('other', '기타')], db_index=True, default='consent', help_text='데이터 처리의 법적 근거', max_length=32),
        ),
        migrations.AddField(
            model_name='feedback',
            name='legal_hold',
            field=models.BooleanField(db_index=True, default=False, help_text='법적 보존 필요 시 True (자동 파기 제외)'),
        ),
        migrations.AlterField(
            model_name='chatquerylog',
            name='client_ip',
            field=models.CharField(blank=True, db_index=True, default='', help_text='요청자 IP의 해시/익명화 표현(원시 IP 미저장)', max_length=64),
        ),
        migrations.AddField(
            model_name='chatquerylog',
            name='consent_log',
            field=models.ForeignKey(blank=True, help_text='실제 동의 증빙 레코드(선택)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_logs', to='ragapp.consentlog'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='consent_log',
            field=models.ForeignKey(blank=True, help_text='실제 동의 증빙 레코드(선택)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='ragapp.consentlog'),
        ),
        migrations.CreateModel(
            name='LegalDocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='예: privacy, terms', max_length=64)),
                ('version', models.CharField(db_index=True, help_text='예: v1, 2025-11-02', max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('content_md', models.TextField(blank=True, default='', help_text='문서 원문(Markdown 등)')),
                ('published_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['-published_at', '-id'],
                'unique_together': {('slug', 'version')},
            },
        ),
        migrations.AddField(
            model_name='consentlog',
            name='document',
            field=models.ForeignKey(blank=True, help_text='동의 당시 사용된 정책/약관 버전(선택)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent_logs', to='ragapp.legaldocumentversion'),
        ),
    ]
