# Generated by Django 5.2.7 on 2025-11-02 04:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragapp', '0013_auditevent_consentlog_dataerasureticket_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(default='AI 뉴스 분석 콘솔', max_length=120)),
                ('effective_date', models.DateField(default=datetime.date.today)),
                ('operator_name', models.CharField(default='김동건', max_length=120)),
                ('contact_email', models.EmailField(blank=True, default='privacy@example.com', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=50)),
                ('consent_gate_enabled', models.BooleanField(default=True)),
                ('privacy_html', models.TextField(blank=True, default='')),
                ('cross_border_html', models.TextField(blank=True, default='')),
                ('tester_html', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '법적 설정',
                'verbose_name_plural': '법적 설정',
            },
        ),
    ]
