# Generated by Django 5.2.7 on 2025-11-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragapp', '0014_legalconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='RagChunk',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('unique_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('doc_id', models.CharField(blank=True, db_index=True, max_length=191)),
                ('url', models.URLField(blank=True)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('text', models.TextField()),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('embedding', models.BinaryField()),
                ('dim', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['doc_id'], name='ragapp_ragc_doc_id_455849_idx'), models.Index(fields=['created_at'], name='ragapp_ragc_created_121cce_idx')],
            },
        ),
    ]
