# Generated by Django 5.2.7 on 2025-11-10 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragapp', '0015_ragchunk'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media_assets/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('mime', models.CharField(blank=True, max_length=100)),
                ('size', models.BigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('chroma_id', models.CharField(blank=True, max_length=200)),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TableDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=128)),
                ('csv', models.FileField(upload_to='table_datasets/%Y/%m/')),
                ('row_count', models.IntegerField(default=0)),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
