# Generated by Django 5.2.7 on 2025-11-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragapp', '0016_mediaasset_tabledataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalconfig',
            name='guide_html',
            field=models.TextField(blank=True, default=''),
        ),
    ]
