# Generated by Django 5.2.7 on 2025-11-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragapp', '0017_legalconfig_guide_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalconfig',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='legalconfig',
            name='effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalconfig',
            name='operator_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='legalconfig',
            name='service_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
