# Generated by Django 5.2.7 on 2025-11-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragapp', '0018_alter_legalconfig_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatquerylog',
            name='meta',
            field=models.JSONField(blank=True, default=dict, help_text='요청/클라이언트 메타'),
        ),
        migrations.AddField(
            model_name='chatquerylog',
            name='sources',
            field=models.JSONField(blank=True, default=list, help_text='참고 소스 목록 [{title,url},...]'),
        ),
    ]
