# Generated by Django 5.2.7 on 2025-11-17 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragapp', '0019_chatquerylog_meta_chatquerylog_sources'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=64, unique=True)),
                ('client_label', models.CharField(blank=True, max_length=100)),
                ('last_question', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('waiting', '대기'), ('active', '진행 중'), ('closed', '종료')], default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='chatquerylog',
            name='channel',
            field=models.CharField(blank=True, choices=[('qarag', 'QARAG 위젯'), ('live_console', '실시간 상담 콘솔'), ('api', '외부 API/연동'), ('system', '시스템/배치')], db_index=True, default='qarag', help_text='메시지가 생성된 채널(위젯/실시간콘솔/API 등)', max_length=32),
        ),
        migrations.AddField(
            model_name='chatquerylog',
            name='content',
            field=models.TextField(blank=True, default='', help_text='단일 메시지의 원문(질문/답변/노트 등). QARAG/실시간 상담 콘솔의 공용 대화 로그용 필드로 사용. 기존 question/answer_excerpt와 병행 가능.'),
        ),
        migrations.AddField(
            model_name='chatquerylog',
            name='message_type',
            field=models.CharField(blank=True, choices=[('query', '질문'), ('answer', '답변'), ('note', '노트/코멘트'), ('error', '에러')], db_index=True, default='query', help_text='메시지 유형(query/answer/note/error 등)', max_length=16),
        ),
        migrations.AddField(
            model_name='chatquerylog',
            name='role',
            field=models.CharField(blank=True, choices=[('user', '사용자'), ('assistant', '봇/상담원'), ('system', '시스템')], db_index=True, default='user', help_text='메시지 역할(user/assistant/system)', max_length=16),
        ),
        migrations.AddField(
            model_name='chatquerylog',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='동일 브라우저/상담 세션을 구분하는 ID (QARAG/실시간 콘솔 공용)', max_length=64),
        ),
        migrations.AlterField(
            model_name='chatquerylog',
            name='meta',
            field=models.JSONField(blank=True, default=dict, help_text='요청/클라이언트 메타 (UA, path, 세션정보 등)'),
        ),
        migrations.AddIndex(
            model_name='chatquerylog',
            index=models.Index(fields=['session_id', 'created_at'], name='ragapp_chat_session_c706fc_idx'),
        ),
        migrations.AddIndex(
            model_name='chatquerylog',
            index=models.Index(fields=['channel', 'created_at'], name='ragapp_chat_channel_90c23d_idx'),
        ),
        migrations.AddIndex(
            model_name='chatquerylog',
            index=models.Index(fields=['mode', 'created_at'], name='ragapp_chat_mode_74f03a_idx'),
        ),
        migrations.AddField(
            model_name='livechatroom',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livechat_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
