# Generated by Django 5.2.7 on 2025-11-18 15:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragapp', '0020_livechatroom_chatquerylog_channel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(db_index=True, default='master', help_text='어드민 콘솔에서 보는 방 이름 (예: master / room-1 등)', max_length=64)),
                ('source', models.CharField(default='qarag', help_text='요청 출발지 (예: QARAG, web, etc.)', max_length=32)),
                ('status', models.CharField(choices=[('waiting', '대기'), ('connected', '상담 중'), ('closed', '종료')], db_index=True, default='waiting', max_length=16)),
                ('user_name', models.CharField(blank=True, max_length=80)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, help_text='QARAG에서 상담 요청한 시각')),
                ('connected_at', models.DateTimeField(blank=True, help_text='상담사가 실제로 연결된 시각', null=True)),
                ('ended_at', models.DateTimeField(blank=True, help_text='상담 종료 시각', null=True)),
                ('last_message_at', models.DateTimeField(blank=True, help_text='마지막 메시지가 오간 시각', null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '실시간 상담 세션',
                'verbose_name_plural': '실시간 상담 세션',
                'ordering': ('-created_at',),
            },
        ),
    ]
