# Generated by Django 5.2.7 on 2025-11-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragapp', '0021_livechatsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='livechatsession',
            name='session_note',
            field=models.TextField(blank=True, verbose_name='상담 메모'),
        ),
        migrations.AddField(
            model_name='livechatsession',
            name='session_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='문의 유형'),
        ),
    ]
