# Generated by Django 5.2.7 on 2025-11-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragapp', '0022_livechatsession_session_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livechatsession',
            name='memo',
            field=models.TextField(blank=True, default='', verbose_name='상담 상세 메모'),
        ),
        migrations.AlterField(
            model_name='livechatsession',
            name='session_note',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='livechatsession',
            name='session_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
