# Generated by Django 5.2.7 on 2025-11-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragapp', '0023_livechatsession_memo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=128, unique=True)),
                ('columns', models.JSONField(default=list)),
                ('column_types', models.JSONField(blank=True, default=dict)),
                ('sample_rows', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '표 스키마',
                'verbose_name_plural': '표 스키마',
            },
        ),
    ]
