# Generated by Django 5.2.7 on 2025-11-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragapp', '0024_tableschema'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableSearchRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='설정 이름 (예: 기본 규칙, 실험용 등)', max_length=100)),
                ('table_name', models.CharField(blank=True, help_text='비우면 전체 공통 규칙, 특정 표만 대상으로 할 때 테이블 이름 기입', max_length=100)),
                ('agg_hints_json', models.JSONField(blank=True, default=dict, help_text='집계 키워드 힌트. 예: {"sum": ["합계","총액"], "avg": ["평균"]}')),
                ('column_synonyms_json', models.JSONField(blank=True, default=dict, help_text='컬럼 별칭. 예: {"region": ["지역","지점"], "sales": ["매출","금액"]}')),
                ('numeric_hints_json', models.JSONField(blank=True, default=list, help_text='숫자 컬럼 힌트. 예: ["sales","amount","price"]')),
                ('min_sim', models.FloatField(default=0.35, help_text="임베딩 기반 검색에서 이 값 이상이면 '비슷하다'고 인정 (0~1 사이 권장)")),
                ('hard_filter_enabled', models.BooleanField(default=True, help_text='질문 안의 단어로 한 번 더 하드 필터를 돌릴지 여부')),
                ('is_active', models.BooleanField(default=True, help_text='체크된 규칙만 실제 검색에서 사용')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '표 검색 규칙',
                'verbose_name_plural': '표 검색 규칙',
                'ordering': ['-updated_at', '-id'],
            },
        ),
    ]
