# Generated by Django 5.2.7 on 2025-11-23 09:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragapp', '0025_tablesearchrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livechatroom',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='QaragFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('session_id', models.CharField(blank=True, db_index=True, default='', help_text='QARAG 위젯 session_id 또는 프론트에서 넘긴 세션 식별자', max_length=64)),
                ('question', models.TextField(blank=True, default='', help_text='피드백 대상이 된 질문(요약 또는 원문)')),
                ('answer', models.TextField(blank=True, default='', help_text='피드백 대상이 된 답변(요약 또는 전체)')),
                ('is_helpful', models.BooleanField(blank=True, db_index=True, help_text='👍이면 True, 👎이면 False, 아직 선택 안 했으면 null', null=True)),
                ('comment', models.TextField(blank=True, default='', help_text='사용자가 적어 준 상세 코멘트 (선택)')),
                ('client_ip', models.CharField(blank=True, db_index=True, default='', help_text='요청자 IP의 해시/익명화 표현(원시 IP 미저장)', max_length=64)),
                ('legal_basis', models.CharField(choices=[('consent', '동의(Consent)'), ('contract', '계약 이행(Contract)'), ('legitimate_interest', '정당한 이익(Legitimate Interest)'), ('legal_obligation', '법적 의무(Legal Obligation)'), ('other', '기타')], db_index=True, default='consent', help_text='데이터 처리의 법적 근거', max_length=32)),
                ('consent_version', models.CharField(blank=True, default='', help_text='동의 문구/문서 버전 문자열(선택)', max_length=32)),
                ('legal_hold', models.BooleanField(db_index=True, default=False, help_text='법적 보존 필요 시 True (자동 파기 제외)')),
                ('delete_at', models.DateTimeField(blank=True, db_index=True, help_text='보존기간 경과 시점(RETENTION_DAYS_QARAG_FEEDBACK 또는 RETENTION_DAYS_FEEDBACK)', null=True)),
                ('extra', models.JSONField(blank=True, help_text='프런트에서 넘기는 부가 데이터(선택)', null=True)),
                ('chat_log', models.ForeignKey(blank=True, help_text='피드백 대상이 된 질문/답변 로그 (대개 assistant 메시지)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qarag_feedbacks', to='ragapp.chatquerylog')),
                ('consent_log', models.ForeignKey(blank=True, help_text='실제 동의 증빙 레코드(선택)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qarag_feedbacks', to='ragapp.consentlog')),
            ],
            options={
                'verbose_name': '질문 챗봇 피드백',
                'verbose_name_plural': '질문 챗봇 피드백',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['session_id', 'created_at'], name='ragapp_qara_session_050325_idx'), models.Index(fields=['is_helpful', 'created_at'], name='ragapp_qara_is_help_3171aa_idx')],
            },
        ),
    ]
