# Generated by Django 5.2.7 on 2025-11-23 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ragapp', '0026_alter_livechatroom_updated_at_qaragfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='RagSearchFeedback',
            fields=[
            ],
            options={
                'verbose_name': 'RAG 검색 피드백',
                'verbose_name_plural': 'RAG 검색 피드백',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ragapp.feedback',),
        ),
        migrations.CreateModel(
            name='WebFeedback',
            fields=[
            ],
            options={
                'verbose_name': '웹 검색 피드백',
                'verbose_name_plural': '웹 검색 피드백',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ragapp.feedback',),
        ),
    ]
