# Generated by Django 5.2.7 on 2025-11-23 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragapp', '0027_ragsearchfeedback_webfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_type', models.CharField(choices=[('web', '웹 검색'), ('rag', 'RAG'), ('qa', '질문 챗봇')], help_text='어떤 채널에서 온 답변인지 (웹 / RAG / 질문 챗봇)', max_length=20)),
                ('from_ui', models.CharField(blank=True, help_text='UI 소스 (예: news_web_panel, news_rag_panel, qaraq_main 등)', max_length=50)),
                ('question', models.TextField(blank=True)),
                ('answer', models.TextField(blank=True)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('helpful', models.BooleanField(blank=True, help_text="사용자가 '도움이 되었어요(👍)' / '조금 아쉬웠어요(👎)' 중 무엇을 눌렀는지", null=True)),
                ('reasons', models.JSONField(blank=True, default=list, help_text='이유 칩 값 배열 (wrong / missing / hard / slow / other 등)')),
                ('comment', models.TextField(blank=True, help_text='사용자가 남긴 자유 코멘트 (선택)')),
                ('stage', models.CharField(blank=True, help_text='thumb / detail / skip 등 어느 단계에서 저장된 피드백인지', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '통합 피드백 로그',
                'verbose_name_plural': '통합 피드백 로그',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FeedbackReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('todo', '할 일'), ('doing', '처리 중'), ('done', '수정 완료'), ('wontfix', '보류 / 적용 안함')], default='todo', max_length=20)),
                ('owner', models.CharField(blank=True, help_text='누가 챙길지 (예: 동건, 프롬프트, UI, 백엔드 등)', max_length=50)),
                ('plan', models.TextField(blank=True, help_text='이 피드백 보고 앞으로 무엇을 해볼지 (TODO 메모)')),
                ('resolution', models.TextField(blank=True, help_text='실제로 어떤 수정/실험을 했는지 기록')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feedback', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='ragapp.feedbacklog')),
            ],
            options={
                'verbose_name': '피드백 리뷰',
                'verbose_name_plural': '피드백 리뷰',
                'ordering': ('-feedback__created_at',),
            },
        ),
    ]
