# Generated by Django 5.2.7 on 2025-11-25 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragapp', '0028_feedbacklog_feedbackreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('DEBUG', 'DEBUG'), ('INFO', 'INFO'), ('WARNING', 'WARNING'), ('ERROR', 'ERROR'), ('CRITICAL', 'CRITICAL')], max_length=10)),
                ('logger_name', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField()),
                ('extra_json', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '애플리케이션 로그',
                'verbose_name_plural': '애플리케이션 로그',
                'ordering': ['-created_at'],
            },
        ),
    ]
