# Generated by Django 5.2.7 on 2025-11-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragapp', '0029_applog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applog',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='applog',
            name='extra_json',
        ),
        migrations.RemoveField(
            model_name='applog',
            name='logger_name',
        ),
        migrations.AddField(
            model_name='applog',
            name='component',
            field=models.CharField(blank=True, help_text='예: upload, ingest, chat, livechat, news_search 등', max_length=50),
        ),
        migrations.AddField(
            model_name='applog',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='applog',
            name='trace_id',
            field=models.CharField(blank=True, db_index=True, help_text='같은 작업(업로드 1번, 질의 1번)을 묶는 ID', max_length=64),
        ),
        migrations.AlterField(
            model_name='applog',
            name='level',
            field=models.CharField(choices=[('DEBUG', 'DEBUG'), ('INFO', 'INFO'), ('WARN', 'WARN'), ('ERROR', 'ERROR')], default='INFO', max_length=10),
        ),
    ]
