# Generated by Django 5.2.7 on 2025-11-26 01:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragapp', '0030_alter_applog_options_remove_applog_extra_json_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='user', max_length=16)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('retention_class', models.CharField(choices=[('normal', '일반(30일)'), ('abuse', '욕설/모욕(증빙보관)'), ('legal_hold', '법무 홀드(수동)')], db_index=True, default='normal', max_length=16)),
                ('purge_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('flagged_at', models.DateTimeField(blank=True, null=True)),
                ('flag_reason', models.CharField(blank=True, default='', max_length=200)),
                ('flagged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flagged_chat_messages', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ragapp.livechatsession')),
            ],
        ),
        migrations.CreateModel(
            name='ChatEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_text', models.TextField()),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('purge_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_chat_evidences', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='ragapp.livechatsession')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ragapp.livechatmessage')),
            ],
        ),
        migrations.AddIndex(
            model_name='livechatmessage',
            index=models.Index(fields=['retention_class', 'purge_at'], name='ragapp_live_retenti_b0940f_idx'),
        ),
        migrations.AddIndex(
            model_name='livechatmessage',
            index=models.Index(fields=['session', 'created_at'], name='ragapp_live_session_9a4395_idx'),
        ),
        migrations.AddIndex(
            model_name='chatevidence',
            index=models.Index(fields=['purge_at'], name='ragapp_chat_purge_a_af1b0a_idx'),
        ),
    ]
