# Generated by Django 5.2.7 on 2025-11-26 02:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragapp', '0031_livechatmessage_chatevidence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurgeRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='running', max_length=16)),
                ('messages_deleted', models.IntegerField(default=0)),
                ('evidences_deleted', models.IntegerField(default=0)),
                ('note', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AlterField(
            model_name='applog',
            name='component',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='applog',
            name='trace_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='actor',
            field=models.CharField(db_index=True, default='system', max_length=64),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='extra',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='target_model',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='target_pk',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='chatquerylog',
            name='message_type',
            field=models.CharField(blank=True, choices=[('query', '질문'), ('answer', '답변'), ('note', '노트/코멘트'), ('error', '에러')], db_index=True, default='query', max_length=16),
        ),
        migrations.AlterField(
            model_name='chatquerylog',
            name='role',
            field=models.CharField(blank=True, choices=[('user', '사용자'), ('assistant', '봇/상담원'), ('system', '시스템')], db_index=True, default='user', max_length=16),
        ),
        migrations.AlterField(
            model_name='chatquerylog',
            name='was_helpful',
            field=models.BooleanField(blank=True, default=None, help_text='True/False/아직없음', null=True),
        ),
        migrations.AlterField(
            model_name='consentlog',
            name='delete_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='정기 파기 대상 시각', null=True),
        ),
        migrations.AlterField(
            model_name='dataerasureticket',
            name='channel',
            field=models.CharField(db_index=True, default='web', max_length=32),
        ),
        migrations.AlterField(
            model_name='dataerasureticket',
            name='processed_by',
            field=models.CharField(blank=True, default='system', max_length=64),
        ),
        migrations.AlterField(
            model_name='dataerasureticket',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='dataerasureticket',
            name='requester_token',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='dataerasureticket',
            name='result_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataerasureticket',
            name='scope',
            field=models.CharField(default='chatlog,feedback,consent', max_length=64),
        ),
        migrations.AlterField(
            model_name='dataerasureticket',
            name='target_ip_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='client_ip',
            field=models.CharField(blank=True, db_index=True, default='', help_text='요청자 IP 해시(원시 IP 미저장)', max_length=64),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='consent_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='ragapp.consentlog'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='consent_version',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='delete_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='RETENTION_DAYS_FEEDBACK', null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='legal_basis',
            field=models.CharField(choices=[('consent', '동의(Consent)'), ('contract', '계약 이행(Contract)'), ('legitimate_interest', '정당한 이익(Legitimate Interest)'), ('legal_obligation', '법적 의무(Legal Obligation)'), ('other', '기타')], db_index=True, default='consent', max_length=32),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='legal_hold',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='feedbacklog',
            name='answer_type',
            field=models.CharField(choices=[('web', '웹 검색'), ('rag', 'RAG'), ('qa', '질문 챗봇')], max_length=20),
        ),
        migrations.AlterField(
            model_name='feedbacklog',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='feedbacklog',
            name='from_ui',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='feedbacklog',
            name='helpful',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacklog',
            name='reasons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='feedbacklog',
            name='stage',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='feedbackreview',
            name='owner',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='feedbackreview',
            name='plan',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='feedbackreview',
            name='resolution',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='livechatsession',
            name='connected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livechatsession',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livechatsession',
            name='last_message_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livechatsession',
            name='room',
            field=models.CharField(db_index=True, default='master', max_length=64),
        ),
        migrations.AlterField(
            model_name='livechatsession',
            name='source',
            field=models.CharField(default='qarag', max_length=32),
        ),
        migrations.AlterField(
            model_name='livechatsession',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='qaragfeedback',
            name='delete_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='RETENTION_DAYS_QARAG_FEEDBACK 또는 RETENTION_DAYS_FEEDBACK', null=True),
        ),
        migrations.AlterField(
            model_name='qaragfeedback',
            name='is_helpful',
            field=models.BooleanField(blank=True, db_index=True, help_text='👍 True / 👎 False / 미선택 null', null=True),
        ),
        migrations.AlterField(
            model_name='tablesearchrule',
            name='agg_hints_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='tablesearchrule',
            name='column_synonyms_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='tablesearchrule',
            name='hard_filter_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tablesearchrule',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tablesearchrule',
            name='min_sim',
            field=models.FloatField(default=0.35),
        ),
        migrations.AlterField(
            model_name='tablesearchrule',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tablesearchrule',
            name='numeric_hints_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='tablesearchrule',
            name='table_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
