# Generated by Django 5.2.7 on 2025-11-26 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragapp', '0032_purgerun_alter_applog_component_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livechatsession',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True),
        ),
    ]
