# Generated by Django 5.2.7 on 2025-11-26 03:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragapp', '0033_livechatsession_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livechatsession',
            name='code',
            field=models.CharField(blank=True, db_index=True, help_text='상담 세션 고유 코드(외부 노출용)', max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='livechatsession',
            name='connected_at',
            field=models.DateTimeField(blank=True, help_text='상담사가 실제로 연결된 시각', null=True),
        ),
        migrations.AlterField(
            model_name='livechatsession',
            name='ended_at',
            field=models.DateTimeField(blank=True, help_text='상담 종료 시각', null=True),
        ),
        migrations.AlterField(
            model_name='livechatsession',
            name='last_message_at',
            field=models.DateTimeField(blank=True, help_text='마지막 메시지가 오간 시각', null=True),
        ),
        migrations.AlterField(
            model_name='livechatsession',
            name='room',
            field=models.CharField(db_index=True, default='master', help_text='어드민 콘솔에서 보는 방 이름 (예: master / client-xxxx 등)', max_length=64),
        ),
        migrations.AlterField(
            model_name='livechatsession',
            name='source',
            field=models.CharField(default='qarag', help_text='요청 출발지 (예: qarag, web, api 등)', max_length=32),
        ),
        migrations.AlterField(
            model_name='livechatsession',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='상담 요청(시작) 시각'),
        ),
        migrations.AlterField(
            model_name='livechatsession',
            name='user_agent',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='livechatsession',
            name='user_name',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
