# Generated by Django 5.2.7 on 2025-11-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragapp', '0034_alter_livechatsession_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livechatsession',
            options={},
        ),
        migrations.RemoveField(
            model_name='livechatsession',
            name='client_ip',
        ),
        migrations.RemoveField(
            model_name='livechatsession',
            name='connected_at',
        ),
        migrations.RemoveField(
            model_name='livechatsession',
            name='last_message_at',
        ),
        migrations.RemoveField(
            model_name='livechatsession',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='livechatsession',
            name='source',
        ),
        migrations.RemoveField(
            model_name='livechatsession',
            name='user_agent',
        ),
        migrations.RemoveField(
            model_name='livechatsession',
            name='user_name',
        ),
        migrations.AddField(
            model_name='livechatsession',
            name='page_path',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='livechatsession',
            name='page_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='livechatsession',
            name='processed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='livechatsession',
            name='session_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livechatsession',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='livechatsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='livechatsession',
            name='ended_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='livechatsession',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livechatsession',
            name='room',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='livechatsession',
            name='session_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livechatsession',
            name='session_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='livechatsession',
            name='started_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='livechatsession',
            name='status',
            field=models.CharField(choices=[('waiting', '대기'), ('active', '진행'), ('ended_need_save', '종료(저장 필요)'), ('saved', '저장 완료'), ('deleted', '삭제됨')], db_index=True, default='waiting', max_length=32),
        ),
        migrations.AddIndex(
            model_name='livechatsession',
            index=models.Index(fields=['status', '-created_at'], name='ragapp_live_status_29d59d_idx'),
        ),
        migrations.AddIndex(
            model_name='livechatsession',
            index=models.Index(fields=['room', '-created_at'], name='ragapp_live_room_c5d702_idx'),
        ),
    ]
