# Generated by Django 5.2.7 on 2025-11-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragapp', '0035_alter_livechatsession_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveChatAbuseKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(help_text='예: 씨발 / fuck / (바보|멍청이)', max_length=128, unique=True, verbose_name='금지어 (키워드 또는 정규식)')),
                ('use_regex', models.BooleanField(default=False, help_text='체크하면 pattern을 정규식으로 해석합니다.', verbose_name='정규식 사용')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용 여부')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
            ],
            options={
                'verbose_name': '상담 욕설/금지어',
                'verbose_name_plural': '상담 욕설/금지어 목록',
            },
        ),
    ]
