# Generated by Django 5.2.7 on 2025-12-01 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragapp', '0036_livechatabusekeyword'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='livechatsession',
            name='assigned_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livechat_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livechatsession',
            name='requested_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedbackreview',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='livechatsession',
            name='status',
            field=models.CharField(choices=[('waiting', '대기'), ('active', '진행'), ('ended', '종료'), ('done', '기록 완료'), ('deleted', '삭제됨')], db_index=True, default='waiting', max_length=32),
        ),
        migrations.AlterField(
            model_name='tablesearchrule',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
