# Generated by Django 5.2.7 on 2025-12-02 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragapp', '0037_livechatsession_assigned_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('client_key', models.CharField(max_length=200)),
                ('web_count', models.PositiveIntegerField(default=0)),
                ('rag_count', models.PositiveIntegerField(default=0)),
                ('pdf_count', models.PositiveIntegerField(default=0)),
                ('image_count', models.PositiveIntegerField(default=0)),
                ('table_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['date', 'client_key'], name='ragapp_dail_date_445041_idx')],
                'unique_together': {('date', 'client_key')},
            },
        ),
    ]
