# Generated by Django 5.2.7 on 2025-12-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragapp', '0038_dailyusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyUsageCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('key', models.CharField(db_index=True, max_length=64)),
                ('kind', models.CharField(choices=[('web', '웹 검색'), ('rag', 'RAG 질문'), ('pdf', 'PDF 분석')], max_length=16)),
                ('used', models.PositiveIntegerField(default=0)),
            ],
            options={
                'unique_together': {('date', 'key', 'kind')},
            },
        ),
    ]
