# Generated by Django 5.2.7 on 2025-12-15 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragapp', '0039_dailyusagecounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackreview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tablesearchrule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='PurgeAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_label', models.CharField(max_length=200)),
                ('action', models.CharField(max_length=20)),
                ('cutoff_at', models.DateTimeField()),
                ('retention_days', models.IntegerField(default=0)),
                ('target_rows', models.IntegerField(default=0)),
                ('deleted_rows', models.IntegerField(default=0)),
                ('note', models.CharField(blank=True, default='', max_length=400)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='ragapp_purg_created_fa2ac1_idx'), models.Index(fields=['model_label'], name='ragapp_purg_model_l_9f1b64_idx')],
            },
        ),
    ]
