# Generated by Django 5.2.7 on 2025-12-16 07:16

import ragapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragapp', '0040_alter_feedbackreview_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='legalconfig',
            old_name='effective_date',
            new_name='tester_effective_date',
        ),
        migrations.AddField(
            model_name='legalconfig',
            name='contact_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='legalconfig',
            name='overseas_transfers',
            field=models.JSONField(blank=True, default=ragapp.models.default_overseas_transfers),
        ),
        migrations.AddField(
            model_name='legalconfig',
            name='policy_change_note',
            field=models.TextField(blank=True, default='기술적 구성(저장 방식, 처리 흐름, 로그 항목 등)은 보안/안정성/비용 최적화를 위해 변경될 수 있으며, 변경 시 개인정보 보호 원칙(최소 수집, 목적 제한, 보관기간 준수)을 우선합니다.'),
        ),
        migrations.AddField(
            model_name='legalconfig',
            name='policy_minimization',
            field=models.TextField(blank=True, default='본 서비스는 개인정보 최소 수집을 원칙으로 하며, 이용자가 개인정보를 입력·업로드하지 않도록 안내합니다. 원문 저장은 최소화하고 가능하면 요약/메타데이터 중심으로 처리합니다.'),
        ),
        migrations.AddField(
            model_name='legalconfig',
            name='policy_processing_location',
            field=models.TextField(blank=True, default='본 서비스는 클라우드 인프라 및 AI API를 활용하여 처리하며, 처리 위치(리전/국가)는 공급자 정책 및 운영 상황에 따라 변동될 수 있습니다. 중요 변경사항은 본 문서를 통해 갱신 고지합니다.'),
        ),
        migrations.AddField(
            model_name='legalconfig',
            name='tester_version',
            field=models.CharField(blank=True, default='v1.0', max_length=32),
        ),
        migrations.AddField(
            model_name='legalconfig',
            name='tos_effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legalconfig',
            name='tos_version',
            field=models.CharField(blank=True, default='v1.0', max_length=32),
        ),
    ]
