# Generated by Django 5.2.7 on 2026-01-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragapp', '0041_rename_effective_date_legalconfig_tester_effective_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(db_index=True, max_length=128, unique=True)),
                ('storage_key', models.CharField(db_index=True, max_length=512, unique=True)),
                ('caption', models.TextField(blank=True, default='')),
                ('tags', models.TextField(blank=True, default='')),
                ('search_text', models.TextField(blank=True, default='')),
                ('orig_name', models.CharField(blank=True, default='', max_length=255)),
                ('mime', models.CharField(blank=True, default='', max_length=120)),
                ('sha16', models.CharField(blank=True, default='', max_length=32)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['updated_at'], name='ragapp_imag_updated_d08f5a_idx'), models.Index(fields=['is_deleted', 'updated_at'], name='ragapp_imag_is_dele_7771a1_idx')],
            },
        ),
    ]
