# Generated by Django 5.2.7 on 2026-01-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragapp', '0042_imageasset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyusagecounter',
            name='kind',
            field=models.CharField(choices=[('web', '웹 검색'), ('rag', 'RAG 질문'), ('pdf', 'PDF 분석'), ('image', '이미지 검색'), ('table', '표 검색')], max_length=16),
        ),
    ]
