# Generated by Django 5.2.8 on 2026-02-13 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragapp', '0043_alter_dailyusagecounter_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUploadRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_key', models.CharField(db_index=True, max_length=512, unique=True)),
                ('actor_key', models.CharField(db_index=True, max_length=80)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=16)),
                ('reject_reason', models.TextField(blank=True, default='')),
                ('orig_name', models.CharField(blank=True, default='', max_length=255)),
                ('mime', models.CharField(blank=True, default='', max_length=64)),
                ('size', models.BigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('sha16', models.CharField(blank=True, db_index=True, default='', max_length=16)),
                ('caption', models.TextField(blank=True, default='')),
                ('tags', models.TextField(blank=True, default='')),
                ('ai_meta', models.JSONField(blank=True, default=dict)),
                ('chroma_pid', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_upload_requests_reviewed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_upload_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPenalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_key', models.CharField(db_index=True, max_length=80, unique=True)),
                ('mode', models.CharField(choices=[('NONE', 'None'), ('SUSPENDED', 'Suspended'), ('PERMABAN', 'Permaban')], db_index=True, default='NONE', max_length=16)),
                ('suspended_until', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('last_ip', models.CharField(blank=True, default='', max_length=64)),
                ('last_ua', models.CharField(blank=True, default='', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalties_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
