# Generated by Django 5.2.8 on 2026-02-17 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragapp', '0044_imageuploadrequest_userpenalty'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveChatBlockPattern',
            fields=[
            ],
            options={
                'verbose_name': '상담 차단 패턴',
                'verbose_name_plural': '상담 차단 패턴 목록',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ragapp.livechatabusekeyword',),
        ),
        migrations.AddField(
            model_name='livechatabusekeyword',
            name='kind',
            field=models.CharField(choices=[('abuse', '욕설/모욕'), ('sexual', '성희롱')], db_index=True, default='abuse', max_length=16, verbose_name='분류'),
        ),
        migrations.AlterField(
            model_name='livechatabusekeyword',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='사용 여부'),
        ),
    ]
