# Generated by Django 5.2.8 on 2026-02-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragapp', '0045_livechatblockpattern_livechatabusekeyword_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyusage',
            name='admin_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
