# Generated by Django 5.2.8 on 2026-08-16 10:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragapp', '0048_alter_mediaasset_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrashedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_label', models.CharField(db_index=True, help_text='app_label.model_name (예: ragapp.mediaasset)', max_length=200)),
                ('object_pk', models.CharField(db_index=True, max_length=64)),
                ('object_repr', models.CharField(blank=True, default='', max_length=500)),
                ('data_json', models.JSONField(blank=True, default=dict, help_text='삭제 당시 필드 스냅샷(복구용, django serializers 포맷)')),
                ('file_trash_map', models.JSONField(blank=True, default=dict, help_text='{필드명: 격리보관된 storage key} — 파일이 있는 모델용')),
                ('deleted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('deleted_by', models.CharField(blank=True, default='', max_length=150)),
                ('restored', models.BooleanField(db_index=True, default=False)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('purged', models.BooleanField(db_index=True, default=False)),
                ('purged_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '휴지통 항목',
                'verbose_name_plural': '휴지통',
                'ordering': ['-deleted_at', '-id'],
                'indexes': [models.Index(fields=['model_label', 'deleted_at'], name='ragapp_tras_model_l_4e81d5_idx'), models.Index(fields=['restored', 'purged', 'deleted_at'], name='ragapp_tras_restore_a43bae_idx')],
            },
        ),
    ]
