# Generated by Django 5.2.8 on 2026-08-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragapp', '0049_trashedrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrashSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retention_days', models.PositiveIntegerField(choices=[(0, '사용 안 함(자동 삭제 없음)'), (7, '7일'), (14, '14일'), (30, '30일'), (60, '60일'), (90, '90일')], default=30, help_text='휴지통에 담긴 지 이 기간(일)이 지나면 자동으로 영구 삭제합니다. 0이면 자동 삭제하지 않습니다.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '휴지통 설정',
                'verbose_name_plural': '휴지통 설정',
            },
        ),
    ]
