# Generated by Django 5.2.8 on 2026-08-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragapp', '0050_trashsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyusage',
            name='key_kind',
            field=models.CharField(blank=True, choices=[('cid', '쿠키(브라우저) 기반'), ('ip', 'IP 기반')], db_index=True, default='', help_text='이 행이 쿠키 기반인지 IP 기반인지(통계 중복 집계 방지용)', max_length=8),
        ),
    ]
